SEX_MAP = {
    "male": "男",
    "female": "女",
    "other": "其他",
    "unknown": "未知",
    "男": "男",
    "女": "女",
    "其他": "其他",
    "未知": "未知",
}

RED_KEYWORDS = [
    "chest pain",
    "difficulty breathing",
    "shortness of breath",
    "unconscious",
    "loss of consciousness",
    "severe bleeding",
    "stroke",
    "car accident",
    "convulsion",
    "胸痛",
    "呼吸困难",
    "气短",
    "昏迷",
    "意识不清",
    "大出血",
    "车祸",
    "抽搐",
]

YELLOW_KEYWORDS = [
    "abdominal pain",
    "vomiting",
    "dizziness",
    "headache",
    "fever",
    "cough",
    "nausea",
    "abdominal cramp",
    "腹痛",
    "呕吐",
    "头晕",
    "头痛",
    "发热",
    "发烧",
    "咳嗽",
    "恶心",
]

SYMPTOM_KEYWORDS = {
    "abdominal pain": "腹痛",
    "belly pain": "腹痛",
    "stomach pain": "腹痛",
    "腹痛": "腹痛",
    "肚子痛": "腹痛",
    "肚子疼": "腹痛",
    "胃痛": "腹痛",
    "chest pain": "胸痛",
    "胸痛": "胸痛",
    "fever": "发热",
    "发热": "发热",
    "发烧": "发热",
    "cough": "咳嗽",
    "咳嗽": "咳嗽",
    "vomiting": "呕吐",
    "vomit": "呕吐",
    "呕吐": "呕吐",
    "恶心": "恶心",
    "nausea": "恶心",
    "dizziness": "头晕",
    "头晕": "头晕",
    "headache": "头痛",
    "头痛": "头痛",
    "bleeding": "出血",
    "出血": "出血",
    "drowsiness": "嗜睡",
    "drowsy": "嗜睡",
    "嗜睡": "嗜睡",
    "犯困": "嗜睡",
    "shortness of breath": "气短",
    "difficulty breathing": "呼吸困难",
    "呼吸困难": "呼吸困难",
    "气短": "气短",
    "thirst": "极度口渴",
    "extreme thirst": "极度口渴",
    "口渴": "极度口渴",
    "非常口渴": "极度口渴",
    "极度口渴": "极度口渴",
    "fainting": "晕厥",
    "晕厥": "晕厥",
    "unconscious": "意识丧失",
    "昏迷": "意识丧失",
    "sore throat": "咽痛",
    "throat pain": "咽痛",
    "throat hurts": "咽痛",
    "喉咙痛": "咽痛",
    "嗓子疼": "咽痛",
    "咽痛": "咽痛",
    "咽喉痛": "咽痛",
    "咽口水疼": "咽痛",
    "吞咽痛": "吞咽疼痛",
    "吞咽困难": "吞咽困难",
    "咽不下去": "吞咽困难",
    "声音嘶哑": "声音嘶哑",
    "鼻塞": "鼻塞",
    "流鼻涕": "流涕",
}

TRAUMA_KEYWORDS = [
    "car accident",
    "crash",
    "fall",
    "injury",
    "trauma",
    "车祸",
    "摔伤",
    "外伤",
    "受伤",
    "撞伤",
]

UNKNOWN_TEMPERATURE_PHRASES = [
    "temperature unknown",
    "don't know my temperature",
    "not sure about the temperature",
    "体温未知",
    "不知道体温",
    "没量体温",
    "不清楚体温",
]

ONSET_PHRASES = [
    "today",
    "yesterday",
    "this morning",
    "last night",
    "今天",
    "昨天",
    "今早",
    "今天早上",
    "昨晚",
    "刚刚",
]
